<a href="https://colab.research.google.com/github/Keshav9723/AIML/blob/main/Exp1BasicCommands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import os

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([6.9,8.8,9.1,4.2])
c=a+b
print(c)

[ 7.9 10.8 12.1  8.2]


In [ ]:
c.sort()
print(c)

[ 7.9  8.2 10.8 12.1]


In [ ]:
d=np.array([(1,2,3),(4,5,6)], dtype=float)
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
e=np.array([(6,9,0),(4,2,7)], dtype=float)
print(d+e)

[[ 7. 11.  3.]
 [ 8.  7. 13.]]


In [ ]:
print(d*e)

[[ 6. 18.  0.]
 [16. 10. 42.]]


In [ ]:
g=np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
h=np.ones((3,3))
print(h)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
i=np.arange(10,25,5) #Gives array of numbers from 10 to 25 adding 5 at a time (excluding 25)
print(i)

[10 15 20]


In [ ]:
j=np.linspace(0,2,9) #Gives 9 numbers between 0 and 2
print(j)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
k=np.full((2,2),7) #Creates and 2x2 matriz with all elements as 7
print(k)

[[7 7]
 [7 7]]


In [ ]:
l=np.eye(2) #Generates an identity matriz of order 2x2
print(l)

[[1. 0.]
 [0. 1.]]


In [ ]:
m=np.random.random((2,2)) #Gives 2x2 matrix with random values
print(m)

[[0.4582789  0.69935761]
 [0.99652813 0.67490225]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[ 7.9 10.8 12.1  8.2]
[-5.9 -6.8 -6.1 -0.2]
[ 6.9 17.6 27.3 16.8]
[0.14492754 0.22727273 0.32967033 0.95238095]


In [ ]:
n=np.array([2,4,3,5])
print(np.exp(n))
print(np.sqrt(n))
print(np.sin(n))
print(np.cos(n))
print(np.log(n))


[  7.3890561   54.59815003  20.08553692 148.4131591 ]
[1.41421356 2.         1.73205081 2.23606798]
[ 0.90929743 -0.7568025   0.14112001 -0.95892427]
[-0.41614684 -0.65364362 -0.9899925   0.28366219]
[0.69314718 1.38629436 1.09861229 1.60943791]


In [ ]:
print(a==n) #Give output for each element seprately
print(a<2)
print(np.array_equal(a,n)) #Give one output

[False False  True False]
[ True False False False]
False


In [ ]:
# Save the array 'a' to a file named 'array1.npy'
np.save('array1', a)

# Save arrays 'a' and 'b' into a single compressed file named 'array2.npz'
np.savez('array2', a=a, b=b)
!ls

array1.npy  array2.npz	array.txt  sample_data


In [ ]:
# Load the array stored in 'array1.npy' into a variable
array1 = np.load('array1.npy')

# Print the loaded array to see its contents
print(array1)  # This will display the contents of the array stored in 'array1.npy'


[1 2 3 4]


In [ ]:
# Load the arrays stored in 'array2.npz' into a dictionary-like object called 'loaded_array'
loaded_array = np.load('array2.npz')

# Print the 'loaded_array' object to see its contents, which includes metadata and keys
print(loaded_array)  # This will display the keys and possibly other information stored in 'array2.npz'

# Access and print the array stored under the key 'a' in the 'loaded_array'
print("Loaded Array 1:", loaded_array['a'])  # This will output the array corresponding to the key 'a'

# Access and print the array stored under the key 'b' in the 'loaded_array'
print("Loaded Array 2:", loaded_array['b'])  # This will output the array corresponding to the key 'b'


NpzFile 'array2.npz' with keys: a, b
Loaded Array 1: [1 2 3 4]
Loaded Array 2: [6.9 8.8 9.1 4.2]


In [ ]:
np.savetxt('array.txt', np.array([[6, 9], [7, 8]]), delimiter=',')

# Loading the data from the text file
loaded_txt_array = np.loadtxt('array.txt', delimiter=',')
print("Loaded Text Array:\n", loaded_txt_array)


Loaded Text Array:
 [[6. 9.]
 [7. 8.]]


In [ ]:
# Print the shape (dimensions) of the array 'd'
print(d.shape)  # This will output a tuple representing the dimensions of array 'd', e.g., (rows, columns) for a 2D array

# Print the length (number of elements) along the first axis of the array 'a'
print(len(a))  # This will output the number of elements in the first dimension of array 'a' (i.e., the number of rows in a 2D array)

# Print the number of dimensions of the array 'd'
print(d.ndim)  # This will output the number of dimensions (axes) of array 'd', e.g., 2 for a 2D array

# Print the total number of elements in the array 'a'
print(a.size)

# Print the data type of the elements in the array 'b'
print(b.dtype)


(2, 3)
4
2
4
float64


In [ ]:
print(a.sum())  # This will output the sum of all the elements in array 'a'

print(a.min())  # This will output the smallest value in array 'a'

print(a.mean())  # This will output the average value of the elements in array 'a'


10
1
2.5


In [ ]:
np.append(a,n) #n is added to a

array([1, 2, 3, 4, 2, 4, 3, 5])